### ISSUE TITLE
CubeMX问题~~

### ISSUE THREAD

**Issue by Chen-Ruochen** [peng-zhihui/HelloWord-Keyboard#11]
想问一下up主，新版本的CubeMX好像不支持生成SW4STM32，有没有什么好的解决办法呀？还是只能用老版本的。

**Comment by zhdjet** [comment]
可以生成STM32CubeIDE代码,用STM32CubeIDE或Clion编译.

**Comment by Chen-Ruochen** [comment]
感谢，我先试试哈

**Comment by Chen-Ruochen** [comment]
十分感谢！之前一直以为clion只能编译sw4stm32的工程
