### ISSUE TITLE
PCB.

### ISSUE THREAD

**Issue by KO-07** [peng-zhihui/HelloWord-Keyboard#114]
Hi sorry to be a bother  but I just wanted to ask if the pcb files are still being prototyped or if they are out elsewhere.

**Comment by KerrLiu** [comment]
here!
https://oshwhub.com/pengzhihui/b11afae464c54a3e8d0f77e1f92dc7b7

**Comment by KerrLiu** [comment]
Some problems with PCB files

**Comment by KO-07** [comment]
Thank you .

**Comment by KO-07** [comment]
Will they eventually be placed into github?

**Comment by KerrLiu** [comment]
> 

i don't konw

**Comment by KO-07** [comment]
Oh that's ok thanks for the link tho
