### ISSUE TITLE
关于电机的疑问

### ISSUE THREAD

**Issue by imyip** [peng-zhihui/HelloWord-Keyboard#14]
请问无刷电机组装有分体结构示意图吗？
对于无刷电机用于编码器定位，不太懂径向永磁的作用。

**Comment by Starryccc** [comment]
用的是磁编码器，磁铁粘在电机后面转动就可以获取角度。
![image](https://user-images.githubusercontent.com/14125820/182383068-d43aa684-15bd-422b-8945-bafa0fa62a24.png)

**Comment by imyip** [comment]
> 用的是磁编码器，磁铁粘在电机后面转动就可以获取角度。 ![image](https://user-images.githubusercontent.com/14125820/182383068-d43aa684-15bd-422b-8945-bafa0fa62a24.png)

原来如此，有点懂了，感谢。
