### ISSUE TITLE
未知 USB 设备(设备描述符请求失败)

### ISSUE THREAD

**Issue by xujianle** [peng-zhihui/HelloWord-Keyboard#152]
刷好固件之后显示未知 USB 设备(设备描述符请求失败) win10&win11都有这样的问题，确定不是焊接的问题

**Comment by yr785444662** [comment]
遇到了同样的问题，Win10系统，求大佬教下怎么解决

**Comment by yr785444662** [comment]
找到问题了，是typeC焊接质量不太行，重焊了一下就OK了。
