### ISSUE TITLE
请问有没有大佬知道要哪些芯片啥的

### ISSUE THREAD

**Issue by weibi-briswich** [peng-zhihui/HelloWord-Keyboard#18]

**Comment by GongXiaoBei77** [comment]
主要的芯片就是
`STM32F103CBT6`
`STM32F4`  
`AS5047P`  
`74HC165` 
`FD8288Q`  
`LN3608` 
`SDB628` 
`XW06A` 
`EMB12P03V`
(该部分均从README和Docs/Datasheet中得到信息)
更加具体的可以等立创开源出来,去立创看

**Comment by xingrz** [comment]
键盘本体：

* STM32F103CBT6 主控
* 74HC165D 位移寄存器 (11 颗)
* XW06A 触控

底座：

* TP4056 电池充电芯片
* 一颗1分4的 USB Hub，具体型号没说

Dynamic 部分没仔细看。
