### ISSUE TITLE
关于触摸IC处的重复上拉

### ISSUE THREAD

**Issue by xingrz** [peng-zhihui/HelloWord-Keyboard#29]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/288288/182524362-f973bdb4-a97a-4662-b03b-1a584bb290de.png">

在 U13 74HC165 处本来就有排阻 RN11、RN22 作 10K 上拉的情况下，触摸芯片 U14 处仍然做了画了一排 10K 上拉。不知道是笔误还是有意为之？

**Comment by yangbo254** [comment]
老哥眼神真好。

**Comment by peng-zhihui** [comment]
可以去掉，这样相当于5K上拉，也不影响。
