### ISSUE TITLE
Would it be possible to open-source the f3d project?

### ISSUE THREAD

**Issue by IsThisTheCrustyCrab-was-taken** [peng-zhihui/HelloWord-Keyboard#40]
This would be cool because it would enable modification/extension of the design (I really like the concept but would like to simplify it a bit to look a bit more minimalist). Should also solve #17 .

**Comment by ru8lq0005** [comment]
The author's friend is said that the pcb board still has some problems in solving, and around August 8 should be announced some other module design，please wait some days.

**Comment by IsThisTheCrustyCrab-was-taken** [comment]
Ab okay, I will, thanks for the reply ^^
