### ISSUE TITLE
up请问一下这个触摸条的问题

### ISSUE THREAD

**Issue by Wangzm007** [peng-zhihui/HelloWord-Keyboard#42]
关于触摸条的设计,有一些疑惑想请教一下up:
- [1 ] 这个触摸PCB板上附着了一层白色材料是什么?是3D树脂还是涂色玻璃或者是乳白色的亚克力板?我想到就这几种.
- [2 ] 白色材料和触摸条PCB板分别有多厚呀?
- [3 ] 它们之间用的什么黏合剂,就普通胶水502之类的吗,普通胶水会不会影响触摸电容之类的.
异常喜爱这个触摸条,劳烦up如有闲暇的话可以解答一下我的疑惑哦,拜谢.

**Comment by peng-zhihui** [comment]
切割的亚克力（Xikii准备用玻璃做）； PCB约薄越好；非导电材质就行
