### ISSUE TITLE
固件中对触控条的处理

### ISSUE THREAD

**Issue by cc0xff** [peng-zhihui/HelloWord-Keyboard#61]
固件中对触控条6个touchpad做了按键定义，但没有看到扫描后，如果触控有触发，接下来做的处理。
请教下，是我没有找到，还是确实固件中是没有对应处理的，需要后续完善的？

**Comment by peng-zhihui** [comment]
后续会在上位机中直接进行自定义

**Comment by cc0xff** [comment]
谢谢回复。
