### ISSUE TITLE
「基础版」与「扩展版」的区别与升级可能

### ISSUE THREAD

**Issue by XieJinYan1127** [peng-zhihui/HelloWord-Keyboard#87]
背景
1. 想先实现一个简单的键盘，完成后再进行扩展成扩展版

问题
1. 基础版是否只包含一个普通键盘的功能
2. 基础版是否可以后续升级为扩展版
3. 基础版升级到扩展版的方法是否是以下
a. 重新制作支脚（包括外壳与PCB）
b. 制作扩展模块
*键盘部分无需改动？

**Comment by tklovejk** [comment]
1、基础版只有键盘功能
2、可以
3、a、不需要，但需要第一次预留弹簧针位置
      b、需要
键盘无需改动

**Comment by xingrz** [comment]
根据之前 Xikii 在直播中的说法，键盘本体是完全一样的。扩展版的区别仅仅在于支脚。不同尺寸的扩展模块搭配不同长度的支脚。

**Comment by XieJinYan1127** [comment]
> 根据之前 Xikii 在直播中的说法，键盘本体是完全一样的。扩展版的区别仅仅在于支脚。不同尺寸的扩展模块搭配不同长度的支脚。

就是说，如果升级的话，或者更换扩展模块的话，需要重新制作支脚（包括PCB和外壳）？

**Comment by xingrz** [comment]
> > 根据之前 Xikii 在直播中的说法，键盘本体是完全一样的。扩展版的区别仅仅在于支脚。不同尺寸的扩展模块搭配不同长度的支脚。
> 
> 就是说，如果升级的话，或者更换扩展模块的话，需要重新制作支脚（包括PCB和外壳）？

是这么说。反正扩展模块和替换的支脚是一起卖的。

**Comment by peng-zhihui** [comment]
这个跟本仓库内容无关，我不卖东西的，开团的事情去找xikii咨询就好了

**Comment by peng-zhihui** [comment]
基础版和扩展的模块是不耦合的，可以单独使用
