### ISSUE TITLE
请教键盘外壳cnc 材料选择

### ISSUE THREAD

**Issue by lovejoey11** [peng-zhihui/HelloWord-Keyboard#94]
rt
尝试复刻，请教cnc加工选择什么品质的铝合金， 我看有2000，3000，6000系列，不知道哪一系列适合做键盘

**Comment by yamiyamiiiiiiiii** [comment]
目前我看到的键盘cnc铝合金貌似都是6000和7000，你可以参考一下

**Comment by xuexuedan** [comment]
6061的铝材是常用的加工材料之一，
当然如果条件允许7075也是很好的选择。
